/* Published DBCLS illustration: no generated anatomical geometry. */
(()=>{'use strict';
const $=s=>document.querySelector(s),T=AFRAME.THREE,scene=$('a-scene'),board=$('#board');
const points=[
 {name:'Nervo periférico',x:321,y:198,text:'Um nervo reúne fibras nervosas, tecido conjuntivo e vasos. O epineuro envolve o nervo e ocupa espaços entre os fascículos.'},
 {name:'Fascículo',x:207,y:160,text:'Um fascículo é um feixe de fibras dentro do nervo. O perineuro delimita cada fascículo; o endoneuro fica ao redor das fibras individuais.'},
 {name:'Fibra mielinizada',x:75,y:212,text:'Observe o axônio e seu revestimento de mielina. No sistema nervoso periférico, a mielina é formada pelas células de Schwann. Nem toda fibra é mielinizada.'},
 {name:'Axônio',x:31,y:218,text:'O axônio é um prolongamento do neurônio que conduz sinais. Um nervo contém muitos axônios; ele não é um único neurônio.'},
 {name:'Bainha de mielina',x:47,y:223,text:'As camadas de mielina envolvem o axônio nesta fibra. Mielina e endoneuro são estruturas diferentes: o endoneuro é tecido conjuntivo.'}
];
const levels=[{title:'Nervo · organização geral',crop:[0,90,400,230],ids:[2,1,0]},{title:'Fascículo · fibras agrupadas',crop:[130,115,165,185],ids:[1]},{title:'Fibra mielinizada · detalhe',crop:[5,177,140,70],ids:[3,4,2]}];
const state={level:0,names:false,selected:null,revealed:false,ready:false},canvas=document.createElement('canvas');canvas.width=1400;canvas.height=1040;
const ctx=canvas.getContext('2d'),image=new Image();let texture,hits=[];
function box(x,y,w,h,text,active=false){ctx.fillStyle=active?'#226762':'#233c4a';ctx.fillRect(x,y,w,h);ctx.fillStyle='#ecf7f8';ctx.font='25px sans-serif';ctx.textAlign='center';ctx.fillText(text,x+w/2,y+h/2+9);}
function draw(){if(!state.ready)return;const level=levels[state.level];hits=[];ctx.fillStyle='#142531';ctx.fillRect(0,0,1400,1040);ctx.textAlign='left';ctx.fillStyle='#b6f2e5';ctx.font='bold 35px sans-serif';ctx.fillText(level.title,45,55);ctx.font='22px sans-serif';ctx.fillStyle='#afc5d1';ctx.fillText('Ilustração 2D • Ensino técnico • Conteúdo não validado',45,90);
const [sx,sy,sw,sh]=level.crop,r=Math.min(1190/sw,635/sh),w=sw*r,h=sh*r,ox=(1400-w)/2,oy=145+(635-h)/2;
ctx.fillStyle='#f5f6ee';ctx.fillRect(35,125,1330,685);ctx.drawImage(image,sx,sy,sw,sh,ox,oy,w,h);
level.ids.forEach((id,i)=>{const p=points[id],x=ox+(p.x-sx)*r,y=oy+(p.y-sy)*r,labelX=100+i*440,labelY=790;ctx.strokeStyle='#275b68';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(labelX,labelY-25);ctx.stroke();ctx.fillStyle=state.selected===id?'#006d62':'#193c50';ctx.beginPath();ctx.arc(x,y,23,0,Math.PI*2);ctx.fill();ctx.textAlign='center';ctx.fillStyle='white';ctx.font='bold 24px sans-serif';ctx.fillText(String(id+1),x,y+8);ctx.fillStyle='#183847';ctx.font='24px sans-serif';ctx.textAlign='left';ctx.fillText(state.names||(state.revealed&&state.selected===id)?p.name:`Ponto ${id+1}`,labelX-45,labelY);hits.push({x:x-30,y:y-30,w:60,h:60,act:()=>select(id)});});
const buttons=[['Nervo',()=>setLevel(0)],['Fascículo',()=>setLevel(1)],['Fibra',()=>setLevel(2)],[state.names?'Ocultar nomes':'Mostrar nomes',toggleNames],['Revelar',reveal],['Restaurar',reset]];
buttons.forEach(([label,act],i)=>{const x=35+(i%3)*450,y=840+Math.floor(i/3)*82;box(x,y,430,65,label,i===state.level);hits.push({x,y,w:430,h:65,act});});
ctx.textAlign='left';ctx.font='18px sans-serif';ctx.fillStyle='#afc5d1';ctx.fillText('erico / ONO, Hiromasa / DBCLS • CC BY 4.0 • Sem escala física',40,1025);texture.needsUpdate=true;
$('#points').replaceChildren(...level.ids.map(id=>{const b=document.createElement('button');b.textContent=state.names?`${id+1} · ${points[id].name}`:`Ponto ${id+1}`;b.setAttribute('aria-pressed',String(state.selected===id));b.onclick=()=>select(id);return b;}));
document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.level===state.level)));$('#names').textContent=state.names?'Ocultar nomes':'Mostrar nomes';$('#names').setAttribute('aria-pressed',String(state.names));$('#reveal').disabled=state.selected===null;
const show=state.selected!==null&&(state.names||state.revealed);$('#selection').textContent=state.selected===null?'Selecione um ponto na imagem.':show?points[state.selected].name:`Ponto ${state.selected+1} selecionado · nome oculto`;$('#description').textContent=show?points[state.selected].text:'';
}
function select(id){state.selected=id;state.revealed=false;draw();}function setLevel(n){state.level=n;state.selected=null;state.revealed=false;draw();}function toggleNames(){state.names=!state.names;state.revealed=false;draw();}function reveal(){if(state.selected!==null){state.revealed=!state.revealed;draw();}}function reset(){Object.assign(state,{level:0,names:false,selected:null,revealed:false});board.object3D.position.set(0,1.6,-2.3);draw();}
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>setLevel(+b.dataset.level));$('#names').onclick=toggleNames;$('#reveal').onclick=reveal;$('#reset').onclick=reset;
$('#vr').onclick=async()=>{try{await scene.enterVR();}catch(e){$('#selection').textContent='VR indisponível neste navegador. Abra no navegador do Quest.';}};
scene.addEventListener('enter-vr',()=>{$('[camera]').setAttribute('look-controls','enabled',true);});scene.addEventListener('exit-vr',()=>{$('[camera]').setAttribute('look-controls','enabled',false);$('[camera]').object3D.rotation.set(0,0,0);});
function init(){image.onload=()=>{texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;const mesh=new T.Mesh(new T.PlaneGeometry(2.9,2.9*1040/1400),new T.MeshBasicMaterial({map:texture}));board.setObject3D('mesh',mesh);board.classList.add('interactive');board.addEventListener('click',e=>{const uv=e.detail.intersection?.uv;if(!uv)return;const x=uv.x*1400,y=(1-uv.y)*1040;hits.find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h)?.act();});state.ready=true;draw();scene.querySelectorAll('[raycaster]').forEach(e=>e.components.raycaster?.refreshObjects());if(new URLSearchParams(location.search).has('test'))test();};image.onerror=()=>{$('#selection').textContent='Não foi possível carregar a ilustração. Recarregue com internet.';};image.src='nerve.svg';}
function test(){const tests=[];const check=(name,value)=>tests.push({name,pass:!!value});check('Imagem vetorial carregada',image.naturalWidth===400);const colors=new Set();const pixels=ctx.getImageData(100,180,1200,550).data;for(let i=0;i<pixels.length;i+=160)colors.add(pixels[i]+','+pixels[i+1]+','+pixels[i+2]);check('Desenho presente e textura exportável',colors.size>100);check('Plano com textura para desktop e VR',!!board.getObject3D('mesh').material.map);select(0);check('Seleção não revela nome',!$('#description').textContent&&$('#selection').textContent.includes('oculto'));reveal();check('Revelação individual', $('#selection').textContent===points[0].name);setLevel(1);check('Mudança de nível limpa seleção',state.selected===null&&$('#points').children.length===1);setLevel(2);check('Fibra com três pontos', $('#points').children.length===3);toggleNames();check('Nomes visíveis', $('#points').textContent.includes('Axônio'));reset();check('Restauração',state.level===0&&!state.names&&state.selected===null);check('Seis controles dentro da cena VR',hits.length===9);const report=document.createElement('pre');report.id='test-report';report.textContent=JSON.stringify({tests,passed:tests.filter(t=>t.pass).length,total:tests.length},null,2);document.body.append(report);}
scene.hasLoaded?init():scene.addEventListener('loaded',init,{once:true});
})();
