// Generated by scripts/build_delivery.py. Rebuild after each web change.
const VERSION="5568eaae1b86b30b", PREFIX='atlasvr-'+encodeURIComponent(self.registration.scope)+'-', NAME=PREFIX+VERSION;
const FILES=["nerve.html", "nerve.js", "nerve.css", "nerve.svg", "index.html", "app.js", "labels.js", "offline.js", "style-v2.css", "parts.json", "credits.html", "models/cabeca.glb", "vendor/aframe-1.7.1.min.js", "vendor/AFRAME-LICENSE.txt", "self-test.js"];
const base=self.registration.scope;
const urls=FILES.map(p=>new URL(p,base).href);
self.addEventListener('install',event=>event.waitUntil((async()=>{
 const cache=await caches.open(NAME);
 try { await cache.addAll(urls.map(url=>new Request(url,{cache:'reload'}))); }
 catch(error){await caches.delete(NAME);throw error;}
 // Wait for old tabs to close: never mix releases mid-session.
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const name of await caches.keys())if(name.startsWith(PREFIX)&&name!==NAME)await caches.delete(name);
 await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url);if(!url.href.startsWith(base))return;
 const page=new URL('index.html',base);
 if(url.pathname===new URL(base).pathname)url.pathname=page.pathname;
 url.search='';url.hash='';
 if(!urls.includes(url.href))return;
 event.respondWith((async()=>{
  const cache=await caches.open(NAME),saved=await cache.match(url.href);
  return saved||fetch(event.request);
 })());
});
self.addEventListener('message',event=>{
 if(event.data?.type!=='CHECK_LOCAL')return;
 event.waitUntil((async()=>{const cache=await caches.open(NAME);const entries=await Promise.all(urls.map(url=>cache.match(url)));event.ports[0]?.postMessage({version:VERSION,complete:entries.every(Boolean),files:entries.length});})());
});
